### ISSUE TITLE
VOD download stalls after a few seconds

### ISSUE THREAD

**Issue by tuxayo** [crackededed/Xtra#523]
version: 2.33.1

logcat started right before taping to launch the download:
https://paste.chapril.org/?2f908d0e90a154ef#CjwTU1DGGx3dFVnSjPJT7tpSKPrSNs7qQYFFqitRDmFN

End of log was at least 30 seconds after the download stalled. It's still at 19% of a 10 minute 360p clip which usually gets downloaded without issue. 

I can suspend and restart the download to get some more segments in. After something like 10 cycles I was able to get that 10 min of 360p download done.

I stayed on 2.32.4 since a while because I noticed something weird when trying a newer version. So now I took the time to upgrade and investigate.

**Comment by crackededed** [comment]
get logs from this debug build: [app-debug.zip](https://github.com/user-attachments/files/16270735/app-debug.zip)

**Comment by tuxayo** [comment]
debug apk? very nice! It's great to experiment without loosing one's data.

I struggled to reproduce and had to compare every setting: turns out I can reproduce the issue on the debug build by setting simultaneous downloads to 3. (My aim was to have less concurrent connections to a download so the firsts 20 seconds download faster so I can immediately check that the beginning is where i want. With too much connections, the beginning is full of holes and if I play it it quickly do errors. So I had to wait. Maybe I misunderstood and simultaneous downloads doesn't help for that ^^")

I don't have a logcat on hand yet but at least here is the important info i found in case I struggle to get and anonymize logs quickly.

**Comment by TCM-NikolaiScheel** [comment]
I'm running into the same issue. It downloads for about 10-30 seconds when I manually stop & resume, then halts. Were you able to find a solution/workaround?

**Comment by tuxayo** [comment]
@TCM-NikolaiScheel Were you able to get full logs? => https://github.com/crackededed/Xtra/issues/523#issuecomment-2233780790

**Comment by TCM-NikolaiScheel** [comment]
@tuxayo @crackededed Hi there! I tested on the newest version released yesterday, as well as the debug build attached on the 17th. I'm getting the same issue on both builds. VODs will download for a few seconds to a couple minutes, then stall out. Here is the logcat for the debug build:

[logcat.txt](https://github.com/user-attachments/files/16855333/logcat.txt)

I'm not sure if it's relevant, but I noticed there is a repeated warning appearing at the end, which occurred shortly after the download stalled out:

`JobService: onNetworkChanged() not implemented in androidx.work.impl.background.systemjob.SystemJobService. Must override in a subclass.`

Any help or suggestions would be appreciated. Thanks!

**Comment by crackededed** [comment]
try changing battery usage to unrestricted for xtra and restart the device

**Comment by TCM-NikolaiScheel** [comment]
@crackededed I tried this but unfortunately it did not change the behavior on my device.

**Comment by crackededed** [comment]
i think it's fixed now

**Comment by Uniquely6958** [comment]
@crackededed it seems like #546 and #532 may be caused due to the same issue.

**Comment by TCM-NikolaiScheel** [comment]
That did the trick on my end, thanks so much for the help!

**Comment by CelianGdfrd** [comment]
Not fixed for me https://github.com/crackededed/Xtra/issues/532#issuecomment-2348827283

**Comment by crackededed** [comment]
> Not fixed for me [#532 (comment)](https://github.com/crackededed/Xtra/issues/532#issuecomment-2348827283)

which version are you using?

**Comment by CelianGdfrd** [comment]
2.34.1

**Comment by crackededed** [comment]
> 2.34.1

it's fixed in 2.34.3

**Comment by CelianGdfrd** [comment]
Sorry, the dates matched between Github and F-Droid releases (+ Github releases don't have a version in the name), I thought they were the same.

**Comment by tuxayo** [comment]
Confirmed working, thanks for the fix :D
There is still something weird with downloading. It starts strong will full speed. (monitoring device trafic) Then speed decreases, seems like the parallel downloads are failing one by one. Then the last stalls. (same behavior as before the fix) But then it restarts before later failing again. And it loop, it continues downloading at a bit slow speed, stalls, restarts. But it ends up finishing reliably with no manual intervention, this is great!

@crackededed Is it possible to get an updated debug apk so I can try to get logs and create a new ticket for the still strange behavior of VOD downloads?

**Comment by crackededed** [comment]
debug apk isn't going to show anything useful unless the download stops because of an error

**Comment by tuxayo** [comment]
@crackededed Here is a big finding: the download gets progressively slower as the number of .ts files increases. A 360p VOD longer than 3hr start being slower to DL than it's duration.
And initially `com.android.providers.media.module` and `com.android.externalstorage` don't have tons of CPU usage. But when the download starts getting slower and slower. htop shows them as taking the most CPU.

I was able to make a long download (more than 2hr of 480p) go fast again by moving all the already downloaded .ts files into a subdirectory. And moving them to their place made it go slow again.
(so here is a mitigation)

I have a `.nomedia` file at the root of my directory that I designated for clips. The actual cause is still a mystery.

**Comment by crackededed** [comment]
try downloading with the `Download videos to single files` setting turned on. i guess some other app keeps scanning the download folder using MediaStore? maybe when a segment is added it goes through all of the previous ones as well and that's causing the high cpu usage. but i thought that it shouldn't get scanned if the .nomedia file is there. maybe the segments could be downloaded into multiple directories with like 100 segments each and that would kinda fix it

**Comment by tuxayo** [comment]
> try downloading with the Download videos to single files setting turned on

I have overlapping clips so that would cause additional download and additional space used :/
Thanks, that would definitely be a circumvention when there is no downside.



> i guess some other app keeps scanning the download folder using MediaStore?

Since then I noticed that the issue happens when matching existing pieces! Which narrows a lot the scope. So if I redownload the same large VOD or something with a large overlap. It will be terribly slow with zero actual download and zero actual file creation.

So it looks directly related to when xtra is matching pieces/downloading.
Maybe there is something wrong in my system's MediaStore. Which xtra is using right?
Though it's a LineageOS 20 so close enough to AOSP 13 and LOS isn't known to butcher AOSP like phone manufacturer's do.
I'll be trying on other phones.

Additional info: audio only DLs seems to affected with a similar magnitude.
It take 35 sec to check a download of 5 min of audio. When having already 260 .ts file in the same vod directory.
Now I'll add chaos. After duplicating all files to have 520 .ts files. Results: **around 80 sec to check a download of 5 min of audio.**


On another phone: galaxy A04e with stock Android 14.
185 existing .ts files => 21 sec to check a 5 min audio only download
After duplicating all
372 existing .ts files => 55 sec to a check a 5 min audio only download
After duplicating all
744 existing .ts files => 104 sec to a check a 5 min audio only download

Yet another phone: galaxy S4 with lineageos 14 (Android 7)
67 existing .ts files => 26 sec to check a 5 min audio only download
134 existing .ts files => 30 sec to check a 5 min audio only download
267 existing .ts files => 40 sec to check a 5 min audio only download


Ok so checking it's **scaling linearly**. So when downloading the cost of each new .ts file will also grow linearly. Which it why it gets slower and slower.
It can **reproduced by savagely duplicating existing .ts files**.
It can be **reproduced on on quite different ROMs**.

**Comment by tuxayo** [comment]
tl;dr having hundreds of any files the directory where the segments go will make download of that VOD be slower. Even if all segments match (slower than video duration in part of the cases) Likely on Android >= 11 only. So likely due to findFile(). Because it enumerates every file of the directory (wtf!). The current code has the segment uri so there is hope for minimal and safe changes to use that. With `DocumentFile.fromSingleUri()` or `ContentResolver.openFileDescriptor()` or something else.




> try downloading with the Download videos to single files setting turned on

I have part of the time enough overlapping clips so that would cause additional download and additional space used :/
Like a few 15 to 30 min downloads on subtopics of the stream. And a large 3hr download of the whole topic.
Thanks, I didn't though of that, that would definitely be a circumvention when there is no downside.

Another use case is [1].

I don't know if there are other advantages of many .ts files vs concatenating them to a single one (I'm not sure if that's how it's done)

There is at least #714 for 1440p streams.

> i guess some other app keeps scanning the download folder using MediaStore?

Since then I noticed that the issue happens when matching existing pieces! Which narrows a lot the scope. So if I redownload the same large VOD or something with a large overlap. It will be terribly slow with zero actual download and zero actual file creation.

So it looks directly related to when xtra is matching pieces/downloading.
Maybe there is something wrong in my system's MediaStore. Which xtra is using right?
Though it's a LineageOS 20 so close enough to AOSP 13 and LOS isn't known to butcher AOSP like phone manufacturer's do.
I'll be trying on other phones.

Additional info: it can be reproduced on audio only DLs so easier to test. (edit: until I later found that I don't even need to cleanly download long VODs to reproduce the issue)
260 existing .ts files in the same vod directory => 35 sec to check a 5 min audio only download
Now I'll add chaos. After duplicating all files:
520 existing .ts files => 80 sec to check a 5 min audio only download
(Fairphone 3 with LineageOS 20/Android 13)

On another phone: galaxy A04e with stock Android 14.
185 existing .ts files => 21 sec to check a 5 min audio only download
After duplicating all
372 existing .ts files => 55 sec to a check a 5 min audio only download
After duplicating all
744 existing .ts files => 104 sec to a check a 5 min audio only download
(fresh install, all default expect DL set to a directory)

Yet another phone: galaxy S4 with lineageos 14 (Android 7)
67 existing .ts files => 26 sec to check a 5 min audio only download
134 existing .ts files => 30 sec to check a 5 min audio only download
267 existing .ts files => 40 sec to check a 5 min audio only download
532 existing .ts files => 64 sec to check a 5 min audio only download
1066 existing .ts files => 126 sec to check a 5 min audio only download
The slower and slower part is after the length of the DL is displayed. At the very beginning (I'll name it 1st phase), there is no length and the start and stop timestamps are wrong. So the slower and slower part (2nd phase) is before the percentages begin to progress. The percentage progressing looks constant. (3rd phase)
On the other phones, it was the percentage progress (3rd phase) getting slower and slower.
That 2nd phase grows linearly so it end up dominating total time. The total time after that point starts to also double when doubling the number of existing segment files. But I don't think that 2nd phase is a problem when downloading. And it's just a 5 min DL. 3rd phase would dominate again (without being hindered by existing segment files on that Android version) the time if I didn't have a 5 min DL, which is only 32 pieces. It's just a test that shows what takes time.


Ok so it can be **reproduced on two different recent-ish ROMs**. The ticket looks safe to reopen so people find this. To avoid having even more duplicates than #532, #546 and possibility #628 if it happens only on long DLs.
Old ROMs with the **old file API might be immune** to this.
Checking for existing pieces is **scaling linearly** as the download progresses. So when downloading, the cost of each new .ts file will also grow linearly. Which it why it gets slower and slower.
It can **reproduced by savagely duplicating existing .ts files**. Maybe doing it with video DLs make it visible quicker with less pieces.


> maybe the segments could be downloaded into multiple directories with like 100 segments each and that would kinda fix it

I literally did that manually after my previous message when hitting the issue on redownloading a 6hr VOD for which I forgot the last 20 min on a topic.[1] (that another use case for hitting the bug, beside regular long downloads). It would have taken like 12 hr because I already start with almost all the .ts files. (2000 files @ 360p) So it's not linear slowdown, you start on almost terminal velocity which is super slow.

So I manually managed the files and it was possible to finish it in a more reasonable time.

> into multiple directories with like 100 segments

So that would work to prevent the overhead to cross a certain threshold. It should still be a measurable hit on battery usage from DLs and maybe capping the possibility to use all the bandwidth. The current default 10 DLs threads might implicitly have been influenced by the the current issue. A lower value likely would do the same without it. Or the same value would download faster.
**But the result with that workaround would definitely be confortable to use**. This just hints to where to look if there is a meaningful need for improving that area.

**Could the cause be that Xtra for each piece is listing the current files** to see if there are matches?
Oh no it's just simply doing `videoDirectory.findFile(it.uri)`. Then is that what gets slower with the number of files? That would require profiling or messing with the code to see what takes time. I'm guessing too much.

Maybe there is a simple enough solution that doesn't involve a more complex file management to just workaround that issue.

Another test: just having tons of empty files named like "test (37).randomext" is enough to reproduce the issue. Yet more simplification. It's not size, it's not the type. Just the having **enough of any files in the same directory as the segments will do**. Removing them make the "2nd phase" much quicker and the 3rd phase (percentage progress) also. As expected.


> Oh no it's just simply doing `videoDirectory.findFile(it.uri)`. Then is that what gets slower with the number of files?

It might very well be findFile.

https://libreddit.diffraction.dev/r/androiddev/comments/orytnx/fixing_treedocumentfilefindfile_lousy_performance/

> findFile() is implemented in DocumentFile as:

```
 public DocumentFile findFile(@NonNull String displayName) {
        for (DocumentFile doc : listFiles()) {
            if (displayName.equals(doc.getName())) {
                return doc;
            }
        }
        return null;
    }
```
https://github.com/androidx/androidx/blob/androidx-main/documentfile/documentfile/src/main/java/androidx/documentfile/provider/DocumentFile.java#L335

It's not a joke 😱😱😱😱 

The is the worst for an app that downloading tons of small files.

The post includes a possible helper function. I don't know if it fits Xtra's use.

More around the topic:
https://stackoverflow.com/questions/64842185/android-11-documentfile-findfile-is-too-slow/70841312#70841312
  => https://github.com/anggrayudi/SimpleStorage
https://github.com/ItzNotABug/DocumentFileCompat/blob/master/screenshots/filecompat_directory_perf.jpeg
  => Having the URI can change every thing. I wonder what they used. DocumentFile.fromSingleUri() ?
https://stackoverflow.com/questions/51661385/documentfile-exists-on-a-path-that-doesnt-yet-exist-always-returns-true-due-t/78441595#78441595
https://stackoverflow.com/questions/64842185/android-11-documentfile-findfile-is-too-slow
https://redlib.catsarch.com/r/androiddev/comments/725ee3/documentfile_is_dead_slow_heres/
https://libreddit.diffraction.dev/r/androiddev/comments/mwaqn1/scoped_storage_recap/gvh64r7/?context=3#gvh64r7
  => https://developer.android.com/reference/android/content/ContentResolver#openFileDescriptor(android.net.Uri,%20java.lang.String,%20android.os.CancellationSignal)
https://stackoverflow.com/questions/47366768/how-to-list-all-files-inside-a-directory-including-sub-directories-efficiently
https://redlib.catsarch.com/r/androiddev/comments/kpn68k/android_11_very_slow_file_access_performance/


Hopefully no new dependency is needed.
With either the helper function. Or `DocumentFile.fromSingleUri()` or `ContentResolver.openFileDescriptor()`

Every findFile() in VideoDownloadWorker.kt seems to have the uri when it's for segments.

**Comment by tuxayo** [comment]
Example of stumbling on the issue during use:
I have a 8h30 download. Doing another 30 sec of downloads in the same VOD (no matching segments) takes almost 5 min

It took 30 sec to display the correct duration of the WIP download (what I named phase 1)
2min30 mark: displaying 33% progress
4min36: jump directly to done (not consistent, I recall seeing 66% in a previous try without a timer)
Making the 8h30 download without cheating by moving the segments from time to time would have taken more than a day.
The m3u8 is created 1st so I can assume from 2min30 to 4min36 it DLs the last 2 segments. (in a file browser, the timestamp of the 3 segments show them on 3 separate minutes, so it looks accurate enough)
So 1 min to download each 10 sec segment.
Damn, it would take like 3 hours to download the last 30 min ^^" Based on this quick and dirty test. (repeated 3 times for the overall duration measurement)

Thankfully the livestream downloads are forced to be done on one file. So they wouldn't go slower than real time after a point. It would have been fun to see my S4  beat an S24 XD
It's still possible that it could happen on very long VODs. Near the 24hr limit.


Deletion of that small DL (don't keep the files):
1 min chronometer mark: now seeing 33% progress
1 min 12 sec mark: now seeing 66% progress
1 min 26 mark: over
So like 13 sec for each deletion of a segment.
Deleting the 8h30 download via the app would take hours.

**Comment by crackededed** [comment]
i think it's working better now. it shouldn't be checking through all of the files anymore

**Comment by tuxayo** [comment]
Testing with
1024 spam files in the existing VOD directory
phone: Fairphone 3
DL: 20 sec of audio

version 2.45.4-DEBUG (c606cf4f4f1e4764a12c432a113aff6fb894902d):
61 sec
(note: inconsistent to reproduce, after all the subsequent tests, now I get 45 sec. So related tests should be done back to back)

version 2.45.5-DEBUG (e93e591dec4055253964b8669552c02b21c3736b):
1 sec

HOLY SHIT this completely negates the impact of existing files.
Thank you so much for the fix ❤️ This will change everything for long downloads.
- Less battery drain.
- Not having a long download being a bother during hours for smaller downloads: If wanting to have them immediately DLed to check if start and end are good.
- Not worry about the download being interrupted by Wi-Fi disconnection and realizing hours later that it has not auto unpaused. And that it still has hours to remain to finish

Other tests. Without existing files.
threads: 2
network speed: phone can DL at more than 12000 KiB/s, Xtra didn't go beyond
- 1400 KiB/s for audio only
- 5000 KiB/s for 720p
So it's not limited by network. No other significant network traffic on the phone or PC sharing the same Wi-Fi.

2.45.4:
DL 5 min of audio : 15 sec
deletion: 6 sec
DL 10 min of audio : 41 sec
deletion: 15 sec
DL 10 min of audio : 41 sec
deletion: 15 sec
DL 20 min of audio : 2min 35sec
deletion: 45 sec
DL 20 min of audio : 2min 17sec
deletion: 49 sec
For each doubling of DL size the time it takes to complete and delete seems to triple. That's why it goes out of hand.


2.45.5:
DL 10 min of audio : 12 sec
deletion: 6 sec
DL 20 min of audio : 22 sec
deletion: 12 sec
DL 20 min of audio : 21 sec
deletion: 11 sec
DL 30 min of audio : 33 sec
deletion: 18 sec
DL 1hr of audio : 1min 05 sec
deletion: 36 sec
DL 2hr of audio : 2 min 10 sec
deletion: 1 min 9 sec
Now it's proportional, each second, it can download 0.9 min of audio :D
And delete 1.7 min of content

This is way faster. I recall that when not having remaining mobile data, I downloaded some stuff in advance. And I couldn't do that at last minute because how long it was due to getting slower and slower. And when I had to leave before it ended, I had no chat because it's downloaded at the end. So 2 min to download 2hrs completely remove these two worries.
Thanks again ❤️ 

The funny thing is now during DL or deletion, the scrolling is a bit sluggish likely due to how much the view and the notification is spammed to refresh the percentage XD (on every segment?) This is a good problem to have :D

**Comment by tuxayo** [comment]
More tests for tuning number of threads

| new segments<br>DLed | existing<br>segments<br>matching | download<br>threads | time | notes                    |
|----------------------|----------------------------------|---------------------|------|--------------------------|
| 30 min               |              0 min                    | 10 (default)        | 1:05 |                          |
| 30 min               |            0 min                      | 20                  | 1:06 |                          |
| 30 min               |                    0 min              | 5                   | 1:08 |                          |
| 30 min               |                                  | 1                   | 1:10 |                          |
| 30 min               |                                  | 2                   | 1:07 |                          |
| 30 min               |                                  | 3                   | 1:09 |                          |
| 30 min               |                                  | 1                   | 1:10 |                          |
| 30 min               | 4 hr 30 min                      | 2                   | 1:51 | 46 sec to match existing |
|                      | 2hr                              | 2                   | 0:20 |                          |
|                      | 2hr                              | 1                   | 0:23 |                          |
|                      | 2hr                              | 3                   | 0:21 |                          |
|                      | 2hr                              | 1                   | 0:23 |                          |
|                      | 2hr                              | 3                   | 0:21 |                          |
|                      | 2hr                              | 2                   | 0:21 |                          |
|                      | 2hr                              | 1                   | 0:26 |                          |
|                      | 2hr                              | 1                   | 0:25 |                          |
|                      | 2hr                              | 2                   | 0:21 |                          |
|                      | 2hr                              | 5                   | 0:23 |                          |
|                      | 2hr                              | 10                  | 0:22 |                          |
|                      | 2hr                              | 20                  | 0:24 |                          |
|                      | 2hr                              | 2                   | 0:24 |                          |
|                      | 2hr                              | 1                   | 0:26 |                          |
|                      | 2hr                              | 2                   | 0:23 |                          |
|                      | 2hr                              | 20                  | 0:23 |                          |
| 10 min               |                                  | 20                  | 1:01 | switch to 720p60fps      |
| 10 min               |                                  | 1                   | 1:00 |                          |
| 10 min               |                                  | 2                   | 0:56 |                          |
| 10 min               |                                  | 1                   | 1:00 |                          |
| 10 min               |                                  | 3                   | 0:57 |                          |
| 10 min               |                                  | 10                  | 0:57 |                          |
| 10 min               |                                  | 2                   | 1:00 |                          |
| 10 min               |                                  | 1                   | 0:58 |                          |
| 10 min               |                                  | 3                   | 0:58 |                          |
| 10 min               |                                  | 1                   | 0:59 |                          |

Inconsistent to reproduce after a while, now I get 0:28 instead of ~0:22 to DL a fully matching 2hr of audio. With a DL with 2800 files in the directory.
edit later: I think I can get + or - 50% so really tests need to be ran right after one another to have a change to be able to compare stuff


Anyway, variance is too great to be able to clearly see a difference with number of workers.
It seem (it might be confirmation bias) for audio only 1 is a tiny bit slower than 2. And beyond it doesn't help nor hurt. (I don't know about RAM usage)
For 720p60 it doesn't seem to make a difference.
There might be a test scenario that shows a greater difference and whose result would outweigh this. I'm open to suggestions for stuff to try. For this in particular or anything else.

Is it sure the concurrent download threads are fully working? The network requests are sequential with threads.
```
07-13 05:46:28.628 13707 13734 I okhttp.OkHttpClient: --> GET https://[...]/480p30/index-dvr.m3u8
07-13 05:46:28.688 13707 13734 I okhttp.OkHttpClient: <-- 200 https://[...]/480p30/index-dvr.m3u8 (59ms)
07-13 05:46:29.867 13707 13734 I okhttp.OkHttpClient: --> GET https://[...]/480p30/360.ts
07-13 05:46:29.989 13707 13734 I okhttp.OkHttpClient: <-- 200 https://[...]/480p30/360.ts (122ms)
07-13 05:46:30.560 13707 13734 I okhttp.OkHttpClient: --> GET https://[...]/480p30/361.ts
07-13 05:46:30.714 13707 13734 I okhttp.OkHttpClient: <-- 200 https://[...]/480p30/361.ts (153ms)
07-13 05:46:31.142 13707 13734 I okhttp.OkHttpClient: --> GET https://[...]/480p30/362.ts
07-13 05:46:31.297 13707 13734 I okhttp.OkHttpClient: <-- 200 https://[...]/480p30/362.ts (154ms)
07-13 05:46:31.839 13707 13734 I okhttp.OkHttpClient: --> GET https://[...]/480p30/363.ts
07-13 05:46:31.994 13707 13734 I okhttp.OkHttpClient: <-- 200 https://[...]/480p30/363.ts (154ms)
07-13 05:46:32.522 13707 13734 I okhttp.OkHttpClient: --> GET https://[...]/480p30/364.ts
07-13 05:46:32.643 13707 13734 I okhttp.OkHttpClient: <-- 200 https://[...]/480p30/364.ts (120ms)
07-13 05:46:33.280 13707 13734 I okhttp.OkHttpClient: --> GET https://[...]/480p30/365.ts
07-13 05:46:33.475 13707 13734 I okhttp.OkHttpClient: <-- 200 https://[...]/480p30/365.ts (194ms)
07-13 05:46:34.113 13707 13734 I okhttp.OkHttpClient: --> GET https://[...]/480p30/366.ts
07-13 05:46:34.274 13707 13734 I okhttp.OkHttpClient: <-- 200 https://[...]/480p30/366.ts (160ms)
07-13 05:46:34.843 13707 13734 I okhttp.OkHttpClient: --> GET https://[...]/480p30/367.ts
07-13 05:46:35.070 13707 13734 I okhttp.OkHttpClient: <-- 200 https://[...]/480p30/367.ts (225ms)
07-13 05:46:35.714 13707 13734 I okhttp.OkHttpClient: --> GET https://[...]/480p30/368.ts
07-13 05:46:35.859 13707 13734 I okhttp.OkHttpClient: <-- 200 https://[...]/480p30/368.ts (144ms)
07-13 05:46:36.276 13707 13734 I okhttp.OkHttpClient: --> GET https://[...]/480p30/369.ts
07-13 05:46:36.400 13707 13734 I okhttp.OkHttpClient: <-- 200 https://[...]/480p30/369.ts (122ms)
07-13 05:46:36.767 13707 13734 I okhttp.OkHttpClient: --> GET https://[...]/480p30/370.ts
07-13 05:46:36.913 13707 13734 I okhttp.OkHttpClient: <-- 200 https://[...]/480p30/370.ts (145ms)
07-13 05:46:37.413 13707 13734 I okhttp.OkHttpClient: --> GET https://[...]/480p30/371.ts
07-13 05:46:37.597 13707 13734 I okhttp.OkHttpClient: <-- 200 https://[...]/480p30/371.ts (183ms)
07-13 05:46:38.184 13707 13734 I okhttp.OkHttpClient: --> GET https://[...]/480p30/372.ts
07-13 05:46:38.330 13707 13734 I okhttp.OkHttpClient: <-- 200 https://[...]/480p30/372.ts (145ms)
07-13 05:46:39.529 13707 13734 I okhttp.OkHttpClient: --> GET https://[...]/480p30/373.ts
07-13 05:46:39.649 13707 13734 I okhttp.OkHttpClient: <-- 200 https://[...]/480p30/373.ts (119ms)
07-13 05:46:40.226 13707 13734 I okhttp.OkHttpClient: --> GET https://[...]/480p30/374.ts
07-13 05:46:40.521 13707 13734 I okhttp.OkHttpClient: <-- 200 https://[...]/480p30/374.ts (294ms)
07-13 05:46:40.962 13707 13734 I okhttp.OkHttpClient: --> GET https://[...]/480p30/375.ts
07-13 05:46:41.102 13707 13734 I okhttp.OkHttpClient: <-- 200 https://[...]/480p30/375.ts (138ms)
07-13 05:46:41.576 13707 13734 I okhttp.OkHttpClient: --> GET https://[...]/480p30/376.ts
07-13 05:46:41.708 13707 13734 I okhttp.OkHttpClient: <-- 200 https://[...]/480p30/376.ts (131ms)
07-13 05:46:42.318 13707 13734 I okhttp.OkHttpClient: --> GET https://[...]/480p30/377.ts
07-13 05:46:42.455 13707 13734 I okhttp.OkHttpClient: <-- 200 https://[...]/480p30/377.ts (136ms)
07-13 05:46:43.259 13707 13734 I okhttp.OkHttpClient: --> GET https://[...]/480p30/378.ts
07-13 05:46:43.394 13707 13734 I okhttp.OkHttpClient: <-- 200 https://[...]/480p30/378.ts (134ms)
07-13 05:46:43.876 13707 13734 I okhttp.OkHttpClient: --> GET https://[...]/480p30/379.ts
07-13 05:46:44.061 13707 13734 I okhttp.OkHttpClient: <-- 200 https://[...]/480p30/379.ts (184ms)
07-13 05:46:44.645 13707 13734 I okhttp.OkHttpClient: --> GET https://[...]/480p30/380.ts
07-13 05:46:44.795 13707 13734 I okhttp.OkHttpClient: <-- 200 https://[...]/480p30/380.ts (149ms)
07-13 05:46:45.486 13707 13734 I okhttp.OkHttpClient: --> GET https://[...]/480p30/381.ts
07-13 05:46:45.632 13707 13734 I okhttp.OkHttpClient: <-- 200 https://[...]/480p30/381.ts (145ms)
07-13 05:46:46.141 13707 13734 I okhttp.OkHttpClient: --> GET https://[...]/480p30/382.ts
07-13 05:46:46.291 13707 13734 I okhttp.OkHttpClient: <-- 200 https://[...]/480p30/382.ts (149ms)
07-13 05:46:46.852 13707 13734 I okhttp.OkHttpClient: --> GET https://[...]/480p30/383.ts
07-13 05:46:46.989 13707 13734 I okhttp.OkHttpClient: <-- 200 https://[...]/480p30/383.ts (136ms)
07-13 05:46:47.475 13707 13734 I okhttp.OkHttpClient: --> GET https://[...]/480p30/384.ts
07-13 05:46:47.635 13707 13734 I okhttp.OkHttpClient: <-- 200 https://[...]/480p30/384.ts (159ms)

```
I still see a difference in the behavior of the percentage displayed reflecting 20 threads finishing at different time causing big pauses and big jumps of the percentage. But the network request progression is sequential and steady.

**Comment by tuxayo** [comment]
Is that expected that a simple download (from clean state) still logs this?
```

**Comment by tuxayo** [comment]
Is that expected that a simple download (from clean state) still logs this?
```
07-13 15:02:36.316 32297 32329 I okhttp.OkHttpClient: <-- END HTTP (203ms, binary NNNNNN-byte body omitted)
07-13 15:02:36.327  2997 20340 I MediaProvider: Observed non-standard /storage/emulated/0/clips/.nomedia
07-13 15:02:36.328  2997 20340 W MediaProvider: isAppCloneUserPair failed. Users: 0 and 0
07-13 15:02:36.328  2997 20340 W MediaProvider: isAppCloneUserPair for user 0: false
07-13 15:02:36.330  2997 20340 V MediaProvider: Inserted id:NNNNNN less than next row id backup:NNNNNN.
07-13 15:02:36.341  2997  6620 I MediaProvider: Observed non-standard /storage/emulated/0/clips/.nomedia
07-13 15:02:36.347  2997  6620 V MediaProvider: Inserted id:NNNNNN less than next row id backup:NNNNNN.
07-13 15:02:36.456 12492 12506 E DatabaseUtils: Writing exception to parcel
07-13 15:02:36.456 12492 12506 E DatabaseUtils: java.lang.IllegalArgumentException: Failed to determine if primary:clips/NNNNNNaudio/1.ts is child of primary:clips: java.io.FileNotFoundException: Missing file for primary:clips/NNNNNNaudio/1.ts at /storage/emulated/0/clips/NNNNNNaudio/1.ts
07-13 15:02:36.456 12492 12506 E DatabaseUtils: 	at com.android.internal.content.FileSystemProvider.isChildDocument(FileSystemProvider.java:145)
07-13 15:02:36.456 12492 12506 E DatabaseUtils: 	at android.provider.DocumentsProvider.enforceTree(DocumentsProvider.java:235)
07-13 15:02:36.456 12492 12506 E DatabaseUtils: 	at android.provider.DocumentsProvider.openAssetFile(DocumentsProvider.java:1347)
07-13 15:02:36.456 12492 12506 E DatabaseUtils: 	at android.content.ContentProvider$Transport.openAssetFile(ContentProvider.java:506)
07-13 15:02:36.456 12492 12506 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:272)
07-13 15:02:36.456 12492 12506 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1280)
07-13 15:02:36.456 12492 12506 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1244)
07-13 15:02:36.456  2997 16099 I MediaProvider: Begin Intent { act=android.intent.action.MEDIA_SCANNER_SCAN_FILE dat=file:///... flg=0xNNNNNN cmp=com.android.providers.media.module/com.android.providers.media.MediaService }
07-13 15:02:36.458 32297 32329 I okhttp.OkHttpClient: --> GET https://d3fi1amfgojobc.cloudfront.net/879a1a9d63d3baed78a4_AAAAAA___NNNNNN_NNNNNN/audio_only/1.ts

```

Another occurrence but this time had more exceptions.

```
07-13 15:28:08.243 12492 12507 E DatabaseUtils: java.lang.IllegalArgumentException: Failed to determine if primary:clips/NNNNNNNaudio is child of primary:clips: java.io.FileNotFoundException: Missing file for primary:clips/NNNNNNNaudio at /storage/emulated/0/clips/NNNNNNNaudio
07-13 15:28:08.243 12492 12507 E DatabaseUtils: 	at com.android.internal.content.FileSystemProvider.isChildDocument(FileSystemProvider.java:145)
07-13 15:28:08.243 12492 12507 E DatabaseUtils: 	at android.provider.DocumentsProvider.enforceTree(DocumentsProvider.java:235)
07-13 15:28:08.243 12492 12507 E DatabaseUtils: 	at android.provider.DocumentsProvider.openAssetFile(DocumentsProvider.java:1347)
07-13 15:28:08.243 12492 12507 E DatabaseUtils: 	at android.content.ContentProvider$Transport.openAssetFile(ContentProvider.java:506)
07-13 15:28:08.243 12492 12507 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:272)
07-13 15:28:08.243 12492 12507 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1280)
07-13 15:28:08.243 12492 12507 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1244)
07-13 15:28:08.250  4642  6877 D conversations: file observer observed new directory creation /storage/emulated/0/clips/NNNNNNNaudio
07-13 15:28:08.257  2997  6620 I MediaProvider: Observed non-standard /storage/emulated/0/clips/.nomedia
07-13 15:28:08.264  2997  6620 W MediaProvider: isAppCloneUserPair failed. Users: 0 and 0
07-13 15:28:08.264  2997  6620 W MediaProvider: isAppCloneUserPair for user 0: false
07-13 15:28:08.265  2997  6620 V MediaProvider: Inserted id:NNNNNNN less than next row id backup:NNNNNNN.
07-13 15:28:08.266  7486  7486 D AndroidRuntime: Calling main entry com.android.commands.content.Content
07-13 15:28:08.273  1496  2542 D CompatibilityChangeReporter: Compat change id reported: NNNNNNN; UID 10164; state: DISABLED
07-13 15:28:08.273  1496  2542 D CompatibilityChangeReporter: Compat change id reported: NNNNNNN; UID 10164; state: DISABLED
07-13 15:28:08.273  1496  2542 D CompatibilityChangeReporter: Compat change id reported: NNNNNNN; UID 10164; state: DISABLED
07-13 15:28:08.273  1496  2542 D CompatibilityChangeReporter: Compat change id reported: NNNNNNN; UID 10164; state: ENABLED
07-13 15:28:08.274  1496  1719 D CompatibilityChangeReporter: Compat change id reported: NNNNNNN; UID 10164; state: ENABLED
07-13 15:28:07.932     0     0 I binder  : 7486:7486 ioctl NNNNNNN 7ffb13f320 returned -22
07-13 15:28:08.284   742   742 D Zygote  : Forked child process 7503
07-13 15:28:08.285  1496  1719 I ActivityManager: Start proc 7503:com.topjohnwu.magisk/u0a164 for content provider {com.topjohnwu.magisk/com.topjohnwu.magisk.core.Provider}
07-13 15:28:08.307  1026  1050 I adbd    : jdwp connection from 7503
07-13 15:28:08.311  2997  6620 I MediaProvider: Scanned external_primary due to REASON_DEMAND, found 1 items in 55ms, 1 inserts 0 updates 0 deletes
07-13 15:28:07.978     0     0 I binder  : 7503:7503 ioctl NNNNNNN 7fd718ff10 returned -22
07-13 15:28:08.318  1496  1857 D CompatibilityChangeReporter: Compat change id reported: NNNNNNN; UID 10164; state: DISABLED
07-13 15:28:08.318  1496  1857 D CompatibilityChangeReporter: Compat change id reported: NNNNNNN; UID 10164; state: DISABLED
07-13 15:28:08.318 12492 12507 E DatabaseUtils: Writing exception to parcel
07-13 15:28:08.318 12492 12507 E DatabaseUtils: java.lang.IllegalArgumentException: Failed to determine if primary:clips/NNNNNNNaudio/NNNNNNN.m3u8 is child of primary:clips: java.io.FileNotFoundException: Missing file for primary:clips/NNNNNNNaudio/NNNNNNN.m3u8 at /storage/emulated/0/clips/NNNNNNNaudio/NNNNNNN.m3u8
07-13 15:28:08.318 12492 12507 E DatabaseUtils: 	at com.android.internal.content.FileSystemProvider.isChildDocument(FileSystemProvider.java:145)
07-13 15:28:08.318 12492 12507 E DatabaseUtils: 	at android.provider.DocumentsProvider.enforceTree(DocumentsProvider.java:235)
07-13 15:28:08.318 12492 12507 E DatabaseUtils: 	at android.provider.DocumentsProvider.openAssetFile(DocumentsProvider.java:1347)
07-13 15:28:08.318 12492 12507 E DatabaseUtils: 	at android.content.ContentProvider$Transport.openAssetFile(ContentProvider.java:506)
07-13 15:28:08.318 12492 12507 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:272)
07-13 15:28:08.318 12492 12507 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1280)
07-13 15:28:08.318 12492 12507 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1244)
07-13 15:28:08.322  7503  7503 D CompatibilityChangeReporter: Compat change id reported: NNNNNNN; UID 10164; state: ENABLED
07-13 15:28:08.328  2997 20271 I MediaProvider: Observed non-standard /storage/emulated/0/clips/.nomedia
07-13 15:28:08.329  2997 20271 W MediaProvider: isAppCloneUserPair failed. Users: 0 and 0
07-13 15:28:08.329  2997 20271 W MediaProvider: isAppCloneUserPair for user 0: false
07-13 15:28:08.331  2997 20271 V MediaProvider: Inserted id:NNNNNNN less than next row id backup:NNNNNNN.
07-13 15:28:08.339  2997  6620 I MediaProvider: Observed non-standard /storage/emulated/0/clips/.nomedia
07-13 15:28:08.346  2997  6620 V MediaProvider: Inserted id:NNNNNNN less than next row id backup:NNNNNNN.
07-13 15:28:08.379  2997 16099 I MediaProvider: Begin Intent { act=android.intent.action.MEDIA_SCANNER_SCAN_FILE dat=file:///... flg=0xNNNNNNN cmp=com.android.providers.media.module/com.android.providers.media.MediaService }
07-13 15:28:08.381  2997 16099 I MediaProvider: Observed non-standard /storage/emulated/0/clips/.nomedia
07-13 15:28:08.423   554   554 E SDM     : HWPrimary::SetRefreshRate: Failed to open /sys/devices/virtual/graphics/fb0/dynamic_fps with error No such file or directory
07-13 15:28:08.424  2997 16099 V MediaProvider: Inserted id:NNNNNNN less than next row id backup:NNNNNNN.
07-13 15:28:08.432 12492 12507 E DatabaseUtils: Writing exception to parcel
07-13 15:28:08.432 12492 12507 E DatabaseUtils: java.lang.IllegalArgumentException: Failed to determine if primary:clips/NNNNNNNaudio/0.ts is child of primary:clips: java.io.FileNotFoundException: Missing file for primary:clips/NNNNNNNaudio/0.ts at /storage/emulated/0/clips/NNNNNNNaudio/0.ts
07-13 15:28:08.432 12492 12507 E DatabaseUtils: 	at com.android.internal.content.FileSystemProvider.isChildDocument(FileSystemProvider.java:145)
07-13 15:28:08.432 12492 12507 E DatabaseUtils: 	at android.provider.DocumentsProvider.enforceTree(DocumentsProvider.java:235)
07-13 15:28:08.432 12492 12507 E DatabaseUtils: 	at android.provider.DocumentsProvider.openAssetFile(DocumentsProvider.java:1347)
07-13 15:28:08.432 12492 12507 E DatabaseUtils: 	at android.content.ContentProvider$Transport.openAssetFile(ContentProvider.java:506)
07-13 15:28:08.432 12492 12507 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:272)
07-13 15:28:08.432 12492 12507 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1280)
07-13 15:28:08.432 12492 12507 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1244)
07-13 15:28:08.434 32297 32330 I okhttp.OkHttpClient: --> GET https://d3fi1amfgojobc.cloudfront.net/879a1a9d63d3baed78a4_AAAAAA___NNNNNNN_NNNNNNN/audio_only/0.ts
07-13 15:28:08.434 32297 32330 I okhttp.OkHttpClient: --> END GET
07-13 15:28:08.452  2997 16099 I MediaProvider: End Intent { act=android.intent.action.MEDIA_SCANNER_SCAN_FILE dat=file:///... flg=0xNNNNNNN cmp=com.android.providers.media.module/com.android.providers.media.MediaService }
07-13 15:28:08.459 32297 32297 I RealImageLoader: 🧠 Successful (MEMORY_CACHE) - /data/user/0/com.github.andreyasadchy.xtra.debug/files/thumbnails/NNNNNNN
07-13 15:28:08.462 32297 32297 I RealImageLoader: 🧠 Successful (MEMORY_CACHE) - /data/user/0/com.github.andreyasadchy.xtra.debug/files/profile_pics/NNNNNNN
07-13 15:28:08.495  7503  7503 V GraphicsEnvironment: ANGLE Developer option for 'com.topjohnwu.magisk' set to: 'default'
07-13 15:28:08.496  7503  7503 V GraphicsEnvironment: ANGLE GameManagerService for com.topjohnwu.magisk: false
07-13 15:28:08.496  7503  7503 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
07-13 15:28:08.499  7503  7503 D NetworkSecurityConfig: No Network Security Config specified, using platform default
07-13 15:28:08.500  7503  7503 D NetworkSecurityConfig: No Network Security Config specified, using platform default
07-13 15:28:08.502 32297 32330 I okhttp.OkHttpClient: <-- 200 https://d3fi1amfgojobc.cloudfront.net/879a1a9d63d3baed78a4_AAAAAA___NNNNNNN_NNNNNNN/audio_only/0.ts (67ms)
07-13 15:28:08.502 32297 32330 I okhttp.OkHttpClient: content-type: video/MP2T
07-13 15:28:08.502 32297 32330 I okhttp.OkHttpClient: content-length: NNNNNNN
07-13 15:28:08.502 32297 32330 I okhttp.OkHttpClient: date: Sun, 13 Jul 2025 12:45:13 GMT
07-13 15:28:08.502 32297 32330 I okhttp.OkHttpClient: last-modified: Thu, 03 Jul 2025 05:56:47 GMT
07-13 15:28:08.502 32297 32330 I okhttp.OkHttpClient: etag: "5b0195f1d0a670bfa98355c6535c5693"
07-13 15:28:08.502 32297 32330 I okhttp.OkHttpClient: x-amz-server-side-encryption: AES256
07-13 15:28:08.502 32297 32330 I okhttp.OkHttpClient: accept-ranges: bytes
07-13 15:28:08.502 32297 32330 I okhttp.OkHttpClient: server: AmazonS3
07-13 15:28:08.502 32297 32330 I okhttp.OkHttpClient: x-cache: Hit from cloudfront
07-13 15:28:08.502 32297 32330 I okhttp.OkHttpClient: via: 1.1 6022b3c50d8e5cfNNNNNNNfNNNNNNN.cloudfront.net (CloudFront)
07-13 15:28:08.502 32297 32330 I okhttp.OkHttpClient: x-amz-cf-pop: MRS53-P2
07-13 15:28:08.502 32297 32330 I okhttp.OkHttpClient: x-amz-cf-id: 4MZdN55-8XJhVi1fV9e3LGnWqdWpzggwZkRw9TEnLK1IpTkZ75CTkA==
07-13 15:28:08.502 32297 32330 I okhttp.OkHttpClient: age: 2577
07-13 15:28:08.558  1496  2094 D CompatibilityChangeReporter: Compat change id reported: NNNNNNN; UID 10164; state: DISABLED
07-13 15:28:08.566  1496  1875 D ConnectivityService: NetReassign [no changes]
07-13 15:28:08.578  7503  7524 D ProfileInstaller: Skipping profile installation for com.topjohnwu.magisk
07-13 15:28:08.587  7503  7503 D CompatibilityChangeReporter: Compat change id reported: NNNNNNN; UID 10164; state: ENABLED
07-13 15:28:08.608  1935  2342 W Parcel  : Expecting binder but got null!
07-13 15:28:08.615  1496  2542 D CoreBackPreview: Window{7acca9f u0 Toast}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@23cd7b5, mPriority=0}
07-13 15:28:08.634  1935  2342 E OpenGLRenderer: Unable to match the desired swap behavior.
07-13 15:28:08.636  7486  7486 D AndroidRuntime: Shutting down VM
07-13 15:28:08.302     0     0 I binder  : 7486:7486 ioctl NNNNNNN 7ffb13f504 returned -22
07-13 15:28:08.780  7535  7535 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
07-13 15:28:08.789  7535  7535 I AndroidRuntime: Using default boot image
07-13 15:28:08.789  7535  7535 I AndroidRuntime: Leaving lock profiling enabled
07-13 15:28:08.795  7535  7535 I com.topjohnwu.magisk:root:0: Core platform API reporting enabled, enforcing=false
07-13 15:28:08.825 32297 32330 I okhttp.OkHttpClient: <-- END HTTP (390ms, binary NNNNNNN-byte body omitted)
07-13 15:28:08.845  2997 20272 I MediaProvider: Observed non-standard /storage/emulated/0/clips/.nomedia
07-13 15:28:08.846  2997 20272 W MediaProvider: isAppCloneUserPair failed. Users: 0 and 0
07-13 15:28:08.846  2997 20272 W MediaProvider: isAppCloneUserPair for user 0: false
07-13 15:28:08.848  2997 20272 V MediaProvider: Inserted id:NNNNNNN less than next row id backup:NNNNNNN.
07-13 15:28:08.863  2997  6620 I MediaProvider: Observed non-standard /storage/emulated/0/clips/.nomedia
07-13 15:28:08.870  2997  6620 V MediaProvider: Inserted id:NNNNNNN less than next row id backup:NNNNNNN.
07-13 15:28:08.946 12492 12507 E DatabaseUtils: Writing exception to parcel
07-13 15:28:08.946 12492 12507 E DatabaseUtils: java.lang.IllegalArgumentException: Failed to determine if primary:clips/NNNNNNNaudio/1.ts is child of primary:clips: java.io.FileNotFoundException: Missing file for primary:clips/NNNNNNNaudio/1.ts at /storage/emulated/0/clips/NNNNNNNaudio/1.ts
07-13 15:28:08.946 12492 12507 E DatabaseUtils: 	at com.android.internal.content.FileSystemProvider.isChildDocument(FileSystemProvider.java:145)
07-13 15:28:08.946 12492 12507 E DatabaseUtils: 	at android.provider.DocumentsProvider.enforceTree(DocumentsProvider.java:235)
07-13 15:28:08.946 12492 12507 E DatabaseUtils: 	at android.provider.DocumentsProvider.openAssetFile(DocumentsProvider.java:1347)
07-13 15:28:08.946 12492 12507 E DatabaseUtils: 	at android.content.ContentProvider$Transport.openAssetFile(ContentProvider.java:506)
07-13 15:28:08.946 12492 12507 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:272)
07-13 15:28:08.946 12492 12507 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1280)
07-13 15:28:08.946 12492 12507 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1244)
07-13 15:28:08.947 32297 32330 I okhttp.OkHttpClient: --> GET https://d3fi1amfgojobc.cloudfront.net/879a1a9d63d3baed78a4_AAAAAA___NNNNNNN_NNNNNNN/audio_only/1.ts
07-13 15:28:08.947 32297 32330 I okhttp.OkHttpClient: --> END GET
07-13 15:28:08.953  2997 16099 I MediaProvider: Begin Intent { act=android.intent.action.MEDIA_SCANNER_SCAN_FILE dat=file:///... flg=0xNNNNNNN cmp=com.android.providers.media.module/com.android.providers.media.MediaService }
07-13 15:28:08.956  2997 16099 I MediaProvider: Observed non-standard /storage/emulated/0/clips/.nomedia
07-13 15:28:08.962  2997 16099 V MediaProvider: Inserted id:NNNNNNN less than next row id backup:NNNNNNN.
07-13 15:28:08.969  2997 16099 I MediaProvider: End Intent { act=android.intent.action.MEDIA_SCANNER_SCAN_FILE dat=file:///... flg=0xNNNNNNN cmp=com.android.providers.media.module/com.android.providers.media.MediaService }
07-13 15:28:08.976  7535  7535 D com.topjohnwu.magisk:root:0: Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
07-13 15:28:08.976  7535  7535 D com.topjohnwu.magisk:root:0: I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt70l.dat
07-13 15:28:08.990  7535  7535 W ziparchive: Unable to open '/data/user_de/0/com.topjohnwu.magisk/cache/main.dm': No such file or directory
07-13 15:28:08.992 32297 32297 I RealImageLoader: 🧠 Successful (MEMORY_CACHE) - /data/user/0/com.github.andreyasadchy.xtra.debug/files/thumbnails/NNNNNNN
07-13 15:28:08.994 32297 32330 I okhttp.OkHttpClient: <-- 200 https://d3fi1amfgojobc.cloudfront.net/879a1a9d63d3baed78a4_AAAAAA___NNNNNNN_NNNNNNN/audio_only/1.ts (46ms)

```



This might actually by the same cause than #718 #719 #717 but the workflow might change if the exception gets caught or not.


Thanks again for that massive improvement. I hope I stumbled on the most concerning regressions that sneaked in that change to such critical stuff as file handling. And that the info in the tickets will help finding the cause.
