### ISSUE TITLE
Concurent deletions can cause a crash

### ISSUE THREAD

**Issue by tuxayo** [crackededed/Xtra#719]
version 2.45.5-DEBUG (https://github.com/crackededed/Xtra/commit/e93e591dec4055253964b8669552c02b21c3736b)

I was chaining full deletions to see if something would blow up:

```
07-13 13:59:17.434  1496  1707 W WindowManager: Exception thrown during dispatchAppVisibility Window{5c9c4d7 u0 com.github.andreyasadchy.xtra.debug/com.github.andreyasadchy.xtra.ui.main.MainActivity EXITING}
07-13 13:59:17.434  1496  1707 W WindowManager: android.os.DeadObjectException
07-13 13:59:17.434  1496  1707 W WindowManager: 	at android.os.BinderProxy.transactNative(Native Method)
07-13 13:59:17.434  1496  1707 W WindowManager: 	at android.os.BinderProxy.transact(BinderProxy.java:584)
07-13 13:59:17.434  1496  1707 W WindowManager: 	at android.view.IWindow$Stub$Proxy.dispatchAppVisibility(IWindow.java:536)
07-13 13:59:17.434  1496  1707 W WindowManager: 	at com.android.server.wm.WindowState.sendAppVisibilityToClients(WindowState.java:3478)
07-13 13:59:17.434  1496  1707 W WindowManager: 	at com.android.server.wm.WindowContainer.sendAppVisibilityToClients(WindowContainer.java:1234)
07-13 13:59:17.434  1496  1707 W WindowManager: 	at com.android.server.wm.WindowToken.setClientVisible(WindowToken.java:392)
07-13 13:59:17.434  1496  1707 W WindowManager: 	at com.android.server.wm.ActivityRecord.setClientVisible(ActivityRecord.java:6825)
07-13 13:59:17.434  1496  1707 W WindowManager: 	at com.android.server.wm.ActivityRecord.onAnimationFinished(ActivityRecord.java:7647)
07-13 13:59:17.434  1496  1707 W WindowManager: 	at com.android.server.wm.ActivityRecord.postApplyAnimation(ActivityRecord.java:5508)
07-13 13:59:17.434  1496  1707 W WindowManager: 	at com.android.server.wm.ActivityRecord.commitVisibility(ActivityRecord.java:5468)
07-13 13:59:17.434  1496  1707 W WindowManager: 	at com.android.server.wm.ActivityRecord.commitVisibility(ActivityRecord.java:5472)
07-13 13:59:17.434  1496  1707 W WindowManager: 	at com.android.server.wm.AppTransitionController.handleClosingApps(AppTransitionController.java:1194)
07-13 13:59:17.434  1496  1707 W WindowManager: 	at com.android.server.wm.AppTransitionController.handleAppTransitionReady(AppTransitionController.java:304)
07-13 13:59:17.434  1496  1707 W WindowManager: 	at com.android.server.wm.RootWindowContainer.checkAppTransitionReady(RootWindowContainer.java:981)
07-13 13:59:17.434  1496  1707 W WindowManager: 	at com.android.server.wm.RootWindowContainer.performSurfacePlacementNoTrace(RootWindowContainer.java:837)
07-13 13:59:17.434  1496  1707 W WindowManager: 	at com.android.server.wm.RootWindowContainer.performSurfacePlacement(RootWindowContainer.java:779)
07-13 13:59:17.434  1496  1707 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop(WindowSurfacePlacer.java:177)
07-13 13:59:17.434  1496  1707 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:126)
07-13 13:59:17.434  1496  1707 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:115)
07-13 13:59:17.434  1496  1707 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer$Traverser.run(WindowSurfacePlacer.java:57)
07-13 13:59:17.434  1496  1707 W WindowManager: 	at android.os.Handler.handleCallback(Handler.java:942)
07-13 13:59:17.434  1496  1707 W WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-13 13:59:17.434  1496  1707 W WindowManager: 	at android.os.Looper.loopOnce(Looper.java:201)
07-13 13:59:17.434  1496  1707 W WindowManager: 	at android.os.Looper.loop(Looper.java:288)
07-13 13:59:17.434  1496  1707 W WindowManager: 	at android.os.HandlerThread.run(HandlerThread.java:67)
07-13 13:59:17.434  1496  1707 W WindowManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
07-13 13:59:17.434  1496  1707 I Process : Sending signal. PID: 19396 SIG: 9
07-13 13:59:17.437  1496 11957 D PackageManager: Instant App installer not found with android.intent.action.INSTALL_INSTANT_APP_PACKAGE

```

I was testing with 3 VOD, so there is definitely concurrency on a same VOD & format.

On reopening the app, the download is shows at "deleting in progress 0%" but it's false, I had to re ask it to get deleted for this to work.

I'm continuing to chaining full deletions:

```
07-13 14:07:40.659  1496  1707 W WindowManager: Failed to deliver inset state change to w=Window{f4561b5 u0 com.github.andreyasadchy.xtra.debug/com.github.andreyasadchy.xtra.ui.main.MainActivity EXITING}
07-13 14:04:43.050  1496  1707 W WindowManager: android.os.DeadObjectException
07-13 14:04:43.050  1496  1707 W WindowManager: 	at android.os.BinderProxy.transactNative(Native Method)
07-13 14:04:43.050  1496  1707 W WindowManager: 	at android.os.BinderProxy.transact(BinderProxy.java:584)
07-13 14:04:43.050  1496  1707 W WindowManager: 	at android.view.IWindow$Stub$Proxy.insetsControlChanged(IWindow.java:473)
07-13 14:04:43.050  1496  1707 W WindowManager: 	at com.android.server.wm.WindowState.notifyInsetsControlChanged(WindowState.java:4023)
07-13 14:04:43.050  1496  1707 W WindowManager: 	at com.android.server.wm.InsetsStateController.lambda$notifyPendingInsetsControlChanged$4$com-android-server-wm-InsetsStateController(InsetsStateController.java:351)
07-13 14:04:43.050  1496  1707 W WindowManager: 	at com.android.server.wm.InsetsStateController$$ExternalSyntheticLambda2.run(Unknown Source:2)
07-13 14:04:43.050  1496  1707 W WindowManager: 	at com.android.server.wm.WindowAnimator.executeAfterPrepareSurfacesRunnables(WindowAnimator.java:345)
07-13 14:04:43.050  1496  1707 W WindowManager: 	at com.android.server.wm.WindowAnimator.animate(WindowAnimator.java:226)
07-13 14:04:43.050  1496  1707 W WindowManager: 	at com.android.server.wm.WindowAnimator.lambda$new$1$com-android-server-wm-WindowAnimator(WindowAnimator.java:106)
07-13 14:04:43.050  1496  1707 W WindowManager: 	at com.android.server.wm.WindowAnimator$$ExternalSyntheticLambda1.doFrame(Unknown Source:2)
07-13 14:04:43.050  1496  1707 W WindowManager: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
07-13 14:04:43.050  1496  1707 W WindowManager: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
07-13 14:04:43.050  1496  1707 W WindowManager: 	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
07-13 14:04:43.050  1496  1707 W WindowManager: 	at android.view.Choreographer.doFrame(Choreographer.java:827)
07-13 14:04:43.050  1496  1707 W WindowManager: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
07-13 14:04:43.050  1496  1707 W WindowManager: 	at android.os.Handler.handleCallback(Handler.java:942)
07-13 14:04:43.050  1496  1707 W WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-13 14:04:43.050  1496  1707 W WindowManager: 	at android.os.Looper.loopOnce(Looper.java:201)
07-13 14:04:43.050  1496  1707 W WindowManager: 	at android.os.Looper.loop(Looper.java:288)
07-13 14:04:43.050  1496  1707 W WindowManager: 	at android.os.HandlerThread.run(HandlerThread.java:67)
07-13 14:04:43.050  1496  1707 W WindowManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
07-13 14:04:43.060  1496  1707 W WindowManager: Exception thrown during dispatchAppVisibility Window{f690d8c u0 com.github.andreyasadchy.xtra.debug/com.github.andreyasadchy.xtra.ui.main.MainActivity EXITING}
07-13 14:04:43.060  1496  1707 W WindowManager: android.os.DeadObjectException
07-13 14:04:43.060  1496  1707 W WindowManager: 	at android.os.BinderProxy.transactNative(Native Method)
07-13 14:04:43.060  1496  1707 W WindowManager: 	at android.os.BinderProxy.transact(BinderProxy.java:584)
07-13 14:04:43.060  1496  1707 W WindowManager: 	at android.view.IWindow$Stub$Proxy.dispatchAppVisibility(IWindow.java:536)
07-13 14:04:43.060  1496  1707 W WindowManager: 	at com.android.server.wm.WindowState.sendAppVisibilityToClients(WindowState.java:3478)
07-13 14:04:43.060  1496  1707 W WindowManager: 	at com.android.server.wm.WindowContainer.sendAppVisibilityToClients(WindowContainer.java:1234)
07-13 14:04:43.060  1496  1707 W WindowManager: 	at com.android.server.wm.WindowToken.setClientVisible(WindowToken.java:392)
07-13 14:04:43.060  1496  1707 W WindowManager: 	at com.android.server.wm.ActivityRecord.setClientVisible(ActivityRecord.java:6825)
07-13 14:04:43.060  1496  1707 W WindowManager: 	at com.android.server.wm.ActivityRecord.onAnimationFinished(ActivityRecord.java:7647)
07-13 14:04:43.060  1496  1707 W WindowManager: 	at com.android.server.wm.ActivityRecord.postApplyAnimation(ActivityRecord.java:5508)
07-13 14:04:43.060  1496  1707 W WindowManager: 	at com.android.server.wm.ActivityRecord.commitVisibility(ActivityRecord.java:5468)
07-13 14:04:43.060  1496  1707 W WindowManager: 	at com.android.server.wm.ActivityRecord.commitVisibility(ActivityRecord.java:5472)
07-13 14:04:43.060  1496  1707 W WindowManager: 	at com.android.server.wm.AppTransitionController.handleClosingApps(AppTransitionController.java:1194)
07-13 14:04:43.060  1496  1707 W WindowManager: 	at com.android.server.wm.AppTransitionController.handleAppTransitionReady(AppTransitionController.java:304)
07-13 14:04:43.060  1496  1707 W WindowManager: 	at com.android.server.wm.RootWindowContainer.checkAppTransitionReady(RootWindowContainer.java:981)
07-13 14:04:43.060  1496  1707 W WindowManager: 	at com.android.server.wm.RootWindowContainer.performSurfacePlacementNoTrace(RootWindowContainer.java:837)
07-13 14:04:43.060  1496  1707 W WindowManager: 	at com.android.server.wm.RootWindowContainer.performSurfacePlacement(RootWindowContainer.java:779)
07-13 14:04:43.060  1496  1707 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop(WindowSurfacePlacer.java:177)
07-13 14:04:43.060  1496  1707 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:126)
07-13 14:04:43.060  1496  1707 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:115)
07-13 14:04:43.060  1496  1707 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer$Traverser.run(WindowSurfacePlacer.java:57)
07-13 14:04:43.060  1496  1707 W WindowManager: 	at android.os.Handler.handleCallback(Handler.java:942)
07-13 14:04:43.060  1496  1707 W WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-13 14:04:43.060  1496  1707 W WindowManager: 	at android.os.Looper.loopOnce(Looper.java:201)
07-13 14:04:43.060  1496  1707 W WindowManager: 	at android.os.Looper.loop(Looper.java:288)
07-13 14:04:43.060  1496  1707 W WindowManager: 	at android.os.HandlerThread.run(HandlerThread.java:67)
07-13 14:04:43.060  1496  1707 W WindowManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
07-13 14:04:43.060  1496  1707 I Process : Sending signal. PID: 27111 SIG: 9

```

Good new, I can get it at will
```
07-13 14:09:29.625  2997  6620 W ModernMediaScanner: Failed to visit /storage/emulated/0/clips/2NNNNNN4audio/331.ts: java.nio.file.NoSuchFileException: /storage/emulated/0/clips/2NNNNN4audio/331.ts
07-13 14:09:29.655  2997  6619 I MediaProvider: Observed non-standard /storage/emulated/0/clips/.nomedia
07-13 14:09:29.665  2997  6619 I MediaProvider: Open with lower FS for /storage/emulated/0/clips/2NNNNNN5audio/1NNNNNNNN6.m3u8. Uid: 10056

07-13 14:09:29.679  2997  6620 I MediaProvider: Scanned external_primary due to REASON_DEMAND, found 0 items in 58ms, 0 inserts 0 updates 0 deletes

07-13 14:09:29.813  2997  1818 I MediaProvider: Deleted 1 0 0 0 0 0 0 items on external_primary due to com.android.externalstorage

07-13 14:09:29.826  2997  6620 I MediaProvider: Observed non-standard /storage/emulated/0/clips/.nomedia
07-13 14:09:29.828  2997  6620 W ModernMediaScanner: Failed to visit /storage/emulated/0/clips/24NNNNNNNN34audio/332.ts: java.nio.file.NoSuchFileException: /storage/emulated/0/clips/2NNNNN34audio/332.ts

07-13 14:09:29.883  2997  6620 I MediaProvider: Scanned external_primary due to REASON_DEMAND, found 0 items in 59ms, 0 inserts 0 updates 0 deletes
07-13 14:09:29.907  1496  1706 W AccessibilityWindowsPopulator: Windows change within in 2 frames continuously over 500 ms and notify windows changed immediately
07-13 14:09:29.921  2997 20271 I MediaProvider: Deleted 1 0 0 0 0 0 0 items on external_primary due to com.android.externalstorage

07-13 14:09:29.936  2997  6620 I MediaProvider: Observed non-standard /storage/emulated/0/clips/.nomedia
07-13 14:09:29.938  2997  6620 W ModernMediaScanner: Failed to visit /storage/emulated/0/clips/NNNNNN4audio/333.ts: java.nio.file.NoSuchFileException: /storage/emulated/0/clips/NNNNNNN34audio/333.ts

07-13 14:09:29.993  2997  6620 I MediaProvider: Scanned external_primary due to REASON_DEMAND, found 0 items in 59ms, 0 inserts 0 updates 0 deletes
07-13 14:09:30.028  2997 20270 I MediaProvider: Deleted 1 0 0 0 0 0 0 items on external_primary due to com.android.externalstorage
07-13 14:09:30.041  2997  6620 I MediaProvider: Observed non-standard /storage/emulated/0/clips/.nomedia
07-13 14:09:30.044  2997  6620 W ModernMediaScanner: Failed to visit /storage/emulated/0/clips/NNNNNaudio/334.ts: java.nio.file.NoSuchFileException: /storage/emulated/0/clips/2NNNN4audio/3NN.ts


07-13 14:09:30.099  2997  6620 I MediaProvider: Scanned external_primary due to REASON_DEMAND, found 0 items in 60ms, 0 inserts 0 updates 0 deletes
07-13 14:09:30.131  2997 20339 I MediaProvider: Deleted 1 0 0 0 0 0 0 items on external_primary due to com.android.externalstorage
07-13 14:09:30.144  2997  6620 I MediaProvider: Observed non-standard /storage/emulated/0/clips/.nomedia
07-13 14:09:30.147  2997  6620 W ModernMediaScanner: Failed to visit /storage/emulated/0/clips/2NNNNN4audio/335.ts: java.nio.file.NoSuchFileException: /storage/emulated/0/clips/2NNNNNNNN34audio/335.ts


07-13 14:09:30.201  2997  6620 I MediaProvider: Scanned external_primary due to REASON_DEMAND, found 0 items in 57ms, 0 inserts 0 updates 0 deletes

07-13 14:09:30.233  2997  8696 I MediaProvider: Deleted 1 0 0 0 0 0 0 items on external_primary due to com.android.externalstorage
07-13 14:09:30.250  2997  6620 I MediaProvider: Observed non-standard /storage/emulated/0/clips/.nomedia
07-13 14:09:30.253  2997  6620 W ModernMediaScanner: Failed to visit /storage/emulated/0/clips/2NNNNNNNN4audio/336.ts: java.nio.file.NoSuchFileException: /storage/emulated/0/clips/2NNNNNNNN4audio/336.ts

07-13 14:09:30.282 12492 12689 E DatabaseUtils: Writing exception to parcel
07-13 14:09:30.282 12492 12689 E DatabaseUtils: java.lang.IllegalArgumentException: Failed to determine if primary:clips/2NNNNNNaudio/1NNNNNNN1.m3u8 is child of primary:clips: java.io.FileNotFoundException: Missing file for primary:clips/2NNNNNNNaudio/NNNNNNN.m3u8 at /storage/emulated/0/clips/2NNNNNNNNN5audio/1NNNNNN1.m3u8
07-13 14:09:30.282 12492 12689 E DatabaseUtils: 	at com.android.internal.content.FileSystemProvider.isChildDocument(FileSystemProvider.java:145)
07-13 14:09:30.282 12492 12689 E DatabaseUtils: 	at android.provider.DocumentsProvider.enforceTree(DocumentsProvider.java:235)
07-13 14:09:30.282 12492 12689 E DatabaseUtils: 	at android.provider.DocumentsProvider.openTypedAssetFileImpl(DocumentsProvider.java:1436)
07-13 14:09:30.282 12492 12689 E DatabaseUtils: 	at android.provider.DocumentsProvider.openTypedAssetFile(DocumentsProvider.java:1376)
07-13 14:09:30.282 12492 12689 E DatabaseUtils: 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:561)
07-13 14:09:30.282 12492 12689 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:327)
07-13 14:09:30.282 12492 12689 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1280)
07-13 14:09:30.282 12492 12689 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1244)
07-13 14:09:30.290 28428 28537 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
07-13 14:09:30.290 28428 28537 E AndroidRuntime: Process: com.github.andreyasadchy.xtra.debug, PID: 28428
07-13 14:09:30.290 28428 28537 E AndroidRuntime: java.lang.IllegalArgumentException: Failed to determine if primary:clips/25NNNNNaudio/1NNNNNN1.m3u8 is child of primary:clips: java.io.FileNotFoundException: Missing file for primary:clips/2NNNNNNNN5audio/1NNNNNN1.m3u8 at /storage/emulated/0/clips/2NNNNNNaudio/1NNNNNNN1.m3u8
07-13 14:09:30.290 28428 28537 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
07-13 14:09:30.290 28428 28537 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
07-13 14:09:30.290 28428 28537 E AndroidRuntime: 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:780)
07-13 14:09:30.290 28428 28537 E AndroidRuntime: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2027)
07-13 14:09:30.290 28428 28537 E AndroidRuntime: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1842)
07-13 14:09:30.290 28428 28537 E AndroidRuntime: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:1518)
07-13 14:09:30.290 28428 28537 E AndroidRuntime: 	at com.github.andreyasadchy.xtra.ui.saved.downloads.DownloadsViewModel$delete$1.invokeSuspend(DownloadsViewModel.kt:746)
07-13 14:09:30.290 28428 28537 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
07-13 14:09:30.290 28428 28537 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
07-13 14:09:30.290 28428 28537 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:124)
07-13 14:09:30.290 28428 28537 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
07-13 14:09:30.290 28428 28537 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
07-13 14:09:30.290 28428 28537 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:820)
07-13 14:09:30.290 28428 28537 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
07-13 14:09:30.290 28428 28537 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)
07-13 14:09:30.290 28428 28537 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4296a3c, Dispatchers.IO]
```

Is that expected that during deletion, there is a flood of
```
07-13 14:20:56.371 29138 29138 I RealImageLoader: 🧠 Successful (MEMORY_CACHE) - /data/user/0/com.github.andreyasadchy.xtra.debug/files/profile_pics/NNNNNNNN
07-13 14:20:56.381 29138 29138 I RealImageLoader: 🧠 Successful (MEMORY_CACHE) - /data/user/0/com.github.andreyasadchy.xtra.debug/files/thumbnails/NNNNNNNN
07-13 14:20:56.385 29138 29138 I RealImageLoader: 🧠 Successful (MEMORY_CACHE) - /data/user/0/com.github.andreyasadchy.xtra.debug/files/profile_pics/NNNNNNNN
07-13 14:20:56.436 29138 29138 I RealImageLoader: 🧠 Successful (MEMORY_CACHE) - /data/user/0/com.github.andreyasadchy.xtra.debug/files/thumbnails/NNNNNNNN
07-13 14:20:56.439 29138 29138 I RealImageLoader: 🧠 Successful (MEMORY_CACHE) - /data/user/0/com.github.andreyasadchy.xtra.debug/files/profile_pics/NNNNNNNN
07-13 14:20:56.449 29138 29138 I RealImageLoader: 🧠 Successful (MEMORY_CACHE) - /data/user/0/com.github.andreyasadchy.xtra.debug/files/thumbnails/NNNNNNNN
07-13 14:20:56.452 29138 29138 I RealImageLoader: 🧠 Successful (MEMORY_CACHE) - /data/user/0/com.github.andreyasadchy.xtra.debug/files/profile_pics/NNNNNNNN
```

It's not when I'm scrolling. At some point, there is a burst of this and the view isn't moving.

The log might be debug only. But that means there is real spamming on the cache layer.

easy way to reproduce the crash without frenetically deleting things:
1. lauch a full deletion
2. open the deletion menu on the same DL
3. wait for the deletion to be over
4. Accept the deleting prompt (full deletion)
5. crash

**Comment by tuxayo** [comment]
This doesn't seem to be #717

**Comment by tuxayo** [comment]
This might be another way to reach 718

**Comment by crackededed** [comment]
fixed

**Comment by crackededed** [comment]
> Is that expected that during deletion, there is a flood of
> 
> ```
> 07-13 14:20:56.371 29138 29138 I RealImageLoader: 🧠 Successful (MEMORY_CACHE) - /data/user/0/com.github.andreyasadchy.xtra.debug/files/profile_pics/NNNNNNNN
> 07-13 14:20:56.381 29138 29138 I RealImageLoader: 🧠 Successful (MEMORY_CACHE) - /data/user/0/com.github.andreyasadchy.xtra.debug/files/thumbnails/NNNNNNNN
> 07-13 14:20:56.385 29138 29138 I RealImageLoader: 🧠 Successful (MEMORY_CACHE) - /data/user/0/com.github.andreyasadchy.xtra.debug/files/profile_pics/NNNNNNNN
> 07-13 14:20:56.436 29138 29138 I RealImageLoader: 🧠 Successful (MEMORY_CACHE) - /data/user/0/com.github.andreyasadchy.xtra.debug/files/thumbnails/NNNNNNNN
> 07-13 14:20:56.439 29138 29138 I RealImageLoader: 🧠 Successful (MEMORY_CACHE) - /data/user/0/com.github.andreyasadchy.xtra.debug/files/profile_pics/NNNNNNNN
> 07-13 14:20:56.449 29138 29138 I RealImageLoader: 🧠 Successful (MEMORY_CACHE) - /data/user/0/com.github.andreyasadchy.xtra.debug/files/thumbnails/NNNNNNNN
> 07-13 14:20:56.452 29138 29138 I RealImageLoader: 🧠 Successful (MEMORY_CACHE) - /data/user/0/com.github.andreyasadchy.xtra.debug/files/profile_pics/NNNNNNNN
> ```

every time download progress is updated the whole item in the recyclerview is reloaded. so thumbnail and everything gets reloaded. it also happens to all items in your download list and if you have multiple downloads and they all refresh everything it gets pretty laggy

**Comment by tuxayo** [comment]
Thanks for the fix. I hope to be able soon to mess again with the app to see if anything still breaks.

**Comment by tuxayo** [comment]
on latest commit: d46fa7fc
I had DL from previous tests that was stuck displaying "deletion in progress 0%"

And trying to fully delete lead to this:
(other deletions worked)

```
07-19 06:46:08.401 21868 21881 E DatabaseUtils: java.lang.IllegalArgumentException: Failed to determine if primary:clips/NNNNNNNNNNNNaudio/NNNNNNNNNNNN.m3u8 is child of primary:clips: java.io.FileNotFoundException: Missing file for primary:clips/NNNNNNNNNNNNaudio/NNNNNNNNNNNN.m3u8 at /storage/emulated/0/clips/NNNNNNNNNNNNaudio/NNNNNNNNNNNN.m3u8
07-19 06:46:08.401 21868 21881 E DatabaseUtils: 	at com.android.internal.content.FileSystemProvider.isChildDocument(FileSystemProvider.java:145)
07-19 06:46:08.401 21868 21881 E DatabaseUtils: 	at android.provider.DocumentsProvider.enforceTree(DocumentsProvider.java:235)
07-19 06:46:08.401 21868 21881 E DatabaseUtils: 	at android.provider.DocumentsProvider.openTypedAssetFileImpl(DocumentsProvider.java:1449)
07-19 06:46:08.401 21868 21881 E DatabaseUtils: 	at android.provider.DocumentsProvider.openTypedAssetFile(DocumentsProvider.java:1389)
07-19 06:46:08.401 21868 21881 E DatabaseUtils: 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:672)
07-19 06:46:08.401 21868 21881 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:341)
07-19 06:46:08.401 21868 21881 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1375)
07-19 06:46:08.401 21868 21881 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1311)
[.....]

07-19 06:46:08.421 21920 21952 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
07-19 06:46:08.421 21920 21952 E AndroidRuntime: Process: com.github.andreyasadchy.xtra.debug, PID: 21920
07-19 06:46:08.421 21920 21952 E AndroidRuntime: java.lang.IllegalArgumentException: Failed to determine if primary:clips/NNNNNNNNNNNNaudio/NNNNNNNNNNNN.m3u8 is child of primary:clips: java.io.FileNotFoundException: Missing file for primary:clips/NNNNNNNNNNNNaudio/NNNNNNNNNNNN.m3u8 at /storage/emulated/0/clips/NNNNNNNNNNNNaudio/NNNNNNNNNNNN.m3u8
07-19 06:46:08.421 21920 21952 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
07-19 06:46:08.421 21920 21952 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
07-19 06:46:08.421 21920 21952 E AndroidRuntime: 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:814)
07-19 06:46:08.421 21920 21952 E AndroidRuntime: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2043)
07-19 06:46:08.421 21920 21952 E AndroidRuntime: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1858)
07-19 06:46:08.421 21920 21952 E AndroidRuntime: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:1528)
07-19 06:46:08.421 21920 21952 E AndroidRuntime: 	at com.github.andreyasadchy.xtra.ui.saved.downloads.DownloadsViewModel$delete$1.invokeSuspend(DownloadsViewModel.kt:742)
07-19 06:46:08.421 21920 21952 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
07-19 06:46:08.421 21920 21952 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
07-19 06:46:08.421 21920 21952 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:124)
07-19 06:46:08.421 21920 21952 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
07-19 06:46:08.421 21920 21952 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
07-19 06:46:08.421 21920 21952 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:820)
07-19 06:46:08.421 21920 21952 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
07-19 06:46:08.421 21920 21952 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)
07-19 06:46:08.421 21920 21952 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4f8e54a, Dispatchers.IO]

[.....]

07-19 06:46:08.747  1306  1335 W WindowManager: Failed to deliver inset control state change to w=Window{ec05602 u0 com.github.andreyasadchy.xtra.debug/com.github.andreyasadchy.xtra.ui.main.MainActivity EXITING}
07-19 06:46:08.747  1306  1335 W WindowManager: android.os.DeadObjectException
07-19 06:46:08.747  1306  1335 W WindowManager: 	at android.os.BinderProxy.transactNative(Native Method)
07-19 06:46:08.747  1306  1335 W WindowManager: 	at android.os.BinderProxy.transact(BinderProxy.java:662)
07-19 06:46:08.747  1306  1335 W WindowManager: 	at android.view.IWindow$Stub$Proxy.insetsControlChanged(IWindow.java:581)
07-19 06:46:08.747  1306  1335 W WindowManager: 	at com.android.server.wm.WindowState.notifyInsetsControlChanged(WindowState.java:4701)
07-19 06:46:08.747  1306  1335 W WindowManager: 	at com.android.server.wm.InsetsStateController.lambda$notifyPendingInsetsControlChanged$3(InsetsStateController.java:422)
07-19 06:46:08.747  1306  1335 W WindowManager: 	at com.android.server.wm.InsetsStateController.$r8$lambda$8yykPRG1GyNq_J17QvL9d5xANMc(InsetsStateController.java:0)
07-19 06:46:08.747  1306  1335 W WindowManager: 	at com.android.server.wm.InsetsStateController$$ExternalSyntheticLambda2.run(R8$$SyntheticClass:0)
07-19 06:46:08.747  1306  1335 W WindowManager: 	at com.android.server.wm.WindowAnimator.executeAfterPrepareSurfacesRunnables(WindowAnimator.java:294)
07-19 06:46:08.747  1306  1335 W WindowManager: 	at com.android.server.wm.RootWindowContainer.performSurfacePlacementNoTrace(RootWindowContainer.java:991)
07-19 06:46:08.747  1306  1335 W WindowManager: 	at com.android.server.wm.RootWindowContainer.performSurfacePlacement(RootWindowContainer.java:926)
07-19 06:46:08.747  1306  1335 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop(WindowSurfacePlacer.java:185)
07-19 06:46:08.747  1306  1335 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:134)
07-19 06:46:08.747  1306  1335 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:123)
07-19 06:46:08.747  1306  1335 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer$Traverser.run(WindowSurfacePlacer.java:65)
07-19 06:46:08.747  1306  1335 W WindowManager: 	at android.os.Handler.handleCallback(Handler.java:958)
07-19 06:46:08.747  1306  1335 W WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-19 06:46:08.747  1306  1335 W WindowManager: 	at android.os.Looper.loopOnce(Looper.java:230)
07-19 06:46:08.747  1306  1335 W WindowManager: 	at android.os.Looper.loop(Looper.java:319)
07-19 06:46:08.747  1306  1335 W WindowManager: 	at android.os.HandlerThread.run(HandlerThread.java:67)
07-19 06:46:08.747  1306  1335 W WindowManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)

[.....]

07-19 06:46:08.829 22020 22020 I Dc.IafdService: handleAppError, pkgName : com.github.andreyasadchy.xtra.debug, userId : 0, errorType : 20, repeat : true component : com.github.andreyasadchy.xtra.ui.saved.downloads.DownloadsViewModel$delete$1.invokeSuspend(DownloadsViewModel.kt:742)errorStack: java.lang.IllegalArgumentException: Failed to determine if primary:clips/NNNNNNNNNNNNaudio/NNNNNNNNNNNN.m3u8 is child of primary:clips: java.io.FileNotFoundException: Missing file for primary:clips/NNNNNNNNNNNNaudio/NNNNNNNNNNNN.m3u8 at /storage/emulated/0/clips/NNNNNNNNNNNNaudio/NNNNNNNNNNNN.m3u8
07-19 06:46:08.829 22020 22020 I Dc.IafdService: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
07-19 06:46:08.829 22020 22020 I Dc.IafdService: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
07-19 06:46:08.829 22020 22020 I Dc.IafdService: 	at android.content.Conte

[.....]

07-19 06:46:09.152  1306  1322 W WindowManager: Exception thrown during dispatchAppVisibility Window{ec05602 u0 com.github.andreyasadchy.xtra.debug/com.github.andreyasadchy.xtra.ui.main.MainActivity EXITING}
07-19 06:46:09.152  1306  1322 W WindowManager: android.os.DeadObjectException
07-19 06:46:09.152  1306  1322 W WindowManager: 	at android.os.BinderProxy.transactNative(Native Method)
07-19 06:46:09.152  1306  1322 W WindowManager: 	at android.os.BinderProxy.transact(BinderProxy.java:662)
07-19 06:46:09.152  1306  1322 W WindowManager: 	at android.view.IWindow$Stub$Proxy.dispatchAppVisibility(IWindow.java:648)
07-19 06:46:09.152  1306  1322 W WindowManager: 	at com.android.server.wm.WindowState.sendAppVisibilityToClients(WindowState.java:4088)
07-19 06:46:09.152  1306  1322 W WindowManager: 	at com.android.server.wm.WindowContainer.sendAppVisibilityToClients(WindowContainer.java:1301)
07-19 06:46:09.152  1306  1322 W WindowManager: 	at com.android.server.wm.WindowToken.setClientVisible(WindowToken.java:446)
07-19 06:46:09.152  1306  1322 W WindowManager: 	at com.android.server.wm.ActivityRecord.setClientVisible(ActivityRecord.java:8121)
07-19 06:46:09.152  1306  1322 W WindowManager: 	at com.android.server.wm.ActivityRecord.postApplyAnimation(ActivityRecord.java:6685)
07-19 06:46:09.152  1306  1322 W WindowManager: 	at com.android.server.wm.ActivityRecord.commitVisibility(ActivityRecord.java:6628)
07-19 06:46:09.152  1306  1322 W WindowManager: 	at com.android.server.wm.Transition.finishTransition(Transition.java:1465)
07-19 06:46:09.152  1306  1322 W WindowManager: 	at com.android.server.wm.TransitionController.finishTransition(TransitionController.java:1113)
07-19 06:46:09.152  1306  1322 W WindowManager: 	at com.android.server.wm.WindowOrganizerController.finishTransition(WindowOrganizerController.java:454)
07-19 06:46:09.152  1306  1322 W WindowManager: 	at android.window.IWindowOrganizerController$Stub.onTransact(IWindowOrganizerController.java:286)
07-19 06:46:09.152  1306  1322 W WindowManager: 	at com.android.server.wm.WindowOrganizerController.onTransact(WindowOrganizerController.java:217)
07-19 06:46:09.152  1306  1322 W WindowManager: 	at android.os.Binder.execTransactInternal(Binder.java:1380)
07-19 06:46:09.152  1306  1322 W WindowManager: 	at android.os.Binder.execTransact(Binder.java:1311)

```

**Comment by tuxayo** [comment]
@crackededed I can still reproduce with 2.45.6

I think that's the 1st stack trace
```
07-21 02:10:49.795 28866 28881 E DatabaseUtils: Writing exception to parcel
07-21 02:10:49.795 28866 28881 E DatabaseUtils: java.lang.IllegalArgumentException: Failed to determine if primary:clips/NNNNNNNNaudio/NNNNNNNN.m3u8 is child of primary:clips: java.io.FileNotFoundException: Missing file for primary:clips/NNNNNNNNaudio/NNNNNNNN.m3u8 at /storage/emulated/0/clips/NNNNNNNNaudio/NNNNNNNN.m3u8
07-21 02:10:49.795 28866 28881 E DatabaseUtils: 	at com.android.internal.content.FileSystemProvider.isChildDocument(FileSystemProvider.java:145)
07-21 02:10:49.795 28866 28881 E DatabaseUtils: 	at android.provider.DocumentsProvider.enforceTree(DocumentsProvider.java:235)
07-21 02:10:49.795 28866 28881 E DatabaseUtils: 	at android.provider.DocumentsProvider.openTypedAssetFileImpl(DocumentsProvider.java:1449)
07-21 02:10:49.795 28866 28881 E DatabaseUtils: 	at android.provider.DocumentsProvider.openTssetypedAFile(DocumentsProvider.java:1389)
07-21 02:10:49.795 28866 28881 E DatabaseUtils: 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:672)
07-21 02:10:49.795 28866 28881 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:341)
07-21 02:10:49.795 28866 28881 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1375)
07-21 02:10:49.795 28866 28881 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1311)
07-21 02:10:49.817  3182 15416 D MediaProvider: Open with FUSE. FilePath: /storage/emulated/0/clips/NNNNNNNNaudio/NNNNNNNN.m3u8. Uid: 10056. Media Capabilities Uid: 0. ShouldRedact: false. ShouldTranscode: false
```


But maybe it's irrelevant, here is the crash. I didn't know until now about the "FATAL EXCEPTION: main" so maybe my previous reports didn't have a relevant stacktrace.

```
07-21 02:11:11.166 29888 29888 E AndroidRuntime: FATAL EXCEPTION: main
07-21 02:11:11.166 29888 29888 E AndroidRuntime: Process: com.github.andreyasadchy.xtra.debug, PID: 29888
07-21 02:11:11.166 29888 29888 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionPagingViewHolder{57cfc72 position=2 id=-1, oldPos=2, pLpos:-1 scrap [attachedScrap] tmpDetached no parent} com.github.andreyasadchy.xtra.ui.view.GridRecyclerView{dc517d7 VFED..... ......I. 0,0-470,1410 #7f0a0275 app:id/recyclerView}, adapter:com.github.andreyasadchy.xtra.ui.saved.downloads.DownloadsAdapter@1750ec9, layout:androidx.recyclerview.widget.GridLayoutManager@178d8c4, context:dagger.hilt.android.internal.managers.ViewComponentManager$FragmentContextWrapper@aNNNNNNNN
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:6686)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6892)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6853)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6849)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2422)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:1251)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1682)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:747)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:837)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4683)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4457)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:5011)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at android.view.View.layout(View.java:25771)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6822)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:689)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at android.view.View.layout(View.java:25771)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6822)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1961)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at android.view.View.layout(View.java:25771)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6822)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at android.view.View.layout(View.java:25771)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6822)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:10523)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1780)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1682)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:747)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4737)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4459)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:5011)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at android.view.View.layout(View.java:25771)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6822)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:535)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at android.view.View.layout(View.java:25771)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6822)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:149)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2365)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:960)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at android.view.View.layout(View.java:25771)
07-21 02:11:11.166 29888 29888 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6822)
07-21 02:11:11.171  4974 30009 I MediaContentSyncTask: [#CMH#] MP time stamp :  NNNNNNNN, CMH time stamp : NNNNNNNN
07-21 02:11:11.171  4974 30009 I MediaContentSyncTask: [#CMH#] Update ITEM :  0
07-21 02:11:11.172  1711  1711 D StatusBarIconController: ignoring old pipeline callbacks, because the new mobile icons are enabled
07-21 02:11:11.175  4974 30009 I BaseThreadPoolExecutor: [#CMH#] afterExecute FutureTask
07-21 02:11:11.176  4974 30009 I ControllerEventHandler: [#CMH#] Alive Privacy Ignored Policy Called:  false
07-21 02:11:11.176  4974  5115 I ControllerEventHandler: [#CMH#] POI Feature is False 
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.view.View.layout(View.java:25771)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6822)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.view.View.layout(View.java:25771)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6822)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1961)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.view.View.layout(View.java:25771)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6822)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.view.View.layout(View.java:25771)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6822)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.view.View.layout(View.java:25771)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6822)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.view.View.layout(View.java:25771)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6822)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.view.View.layout(View.java:25771)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6822)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1084)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.view.View.layout(View.java:25771)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6822)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:5279)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4526)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3288)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11344)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1689)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1153)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:1079)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:958)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:230)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:319)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8919)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
07-21 02:11:11.176 29888 29888 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
07-21 02:11:11.196  3182  7386 I MediaProvider: Deleted 0 0 0 1 0 0 0 items on external_primary due to com.android.externalstorage
07-21 02:11:11.202  1310 30021 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
07-21 02:11:11.203  1310  8139 D Debug   : low && ship && 3rdparty app crash, do not dump
07-21 02:11:11.204  1310  8139 W ActivityTaskManager:   Force finishing activity com.github.andreyasadchy.xtra.debug/com.github.andreyasadchy.xtra.ui.main.MainActivity
07-21 02:11:11.205  1310  8139 D WindowManager: Transition is created, t=TransitionRecord{e27f834 id=-1 type=CLOSE flags=0x10}, caller=com.android.server.wm.TransitionController.createTransition:339 com.android.server.wm.TransitionController.requestTransitionIfNeeded:814 com.android.server.wm.TransitionController.requestTransitionIfNeeded:720 com.android.server.wm.DisplayContent.requestTransitionAndLegacyPrepare:6894 com.android.server.wm.DisplayContent.requestTransitionAndLegacyPrepare:6887 
07-21 02:11:11.205  1310 30022 W ActivityManager: crash : com.github.andreyasadchy.xtra.debug,10247

```

**Comment by tuxayo** [comment]
And I again have a download stuck displaying a deletion in progress (it's false) an that crashes when I try a full delete

```
07-21 03:46:28.802  5187  5201 E DatabaseUtils: Writing exception to parcel
07-21 03:46:28.802  5187  5201 E DatabaseUtils: java.lang.IllegalArgumentException: Failed to determine if primary:clips/NNNNNNNNaudio/NNNNNNNN.m3u8 is child of primary:clips: java.io.FileNotFoundException: Missing file for primary:clips/NNNNNNNNaudio/NNNNNNNN.m3u8 at /storage/emulated/0/clips/NNNNNNNNaudio/NNNNNNNN.m3u8
07-21 03:46:28.802  5187  5201 E DatabaseUtils: 	at com.android.internal.content.FileSystemProvider.isChildDocument(FileSystemProvider.java:145)
07-21 03:46:28.802  5187  5201 E DatabaseUtils: 	at android.provider.DocumentsProvider.enforceTree(DocumentsProvider.java:235)
07-21 03:46:28.802  5187  5201 E DatabaseUtils: 	at android.provider.DocumentsProvider.openTypedAssetFileImpl(DocumentsProvider.java:1449)
07-21 03:46:28.802  5187  5201 E DatabaseUtils: 	at android.provider.DocumentsProvider.openTypedAssetFile(DocumentsProvider.java:1389)
07-21 03:46:28.802  5187  5201 E DatabaseUtils: 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:672)
07-21 03:46:28.802  5187  5201 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:341)
07-21 03:46:28.802  5187  5201 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1375)
07-21 03:46:28.802  5187  5201 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1311)
07-21 03:46:28.820  5037  5082 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
07-21 03:46:28.820  5037  5082 E AndroidRuntime: Process: com.github.andreyasadchy.xtra.debug, PID: 5037
07-21 03:46:28.820  5037  5082 E AndroidRuntime: java.lang.IllegalArgumentException: Failed to determine if primary:clips/NNNNNNNNaudio/NNNNNNNN.m3u8 is child of primary:clips: java.io.FileNotFoundException: Missing file for primary:clips/NNNNNNNNaudio/NNNNNNNN.m3u8 at /storage/emulated/0/clips/NNNNNNNNaudio/NNNNNNNN.m3u8
07-21 03:46:28.820  5037  5082 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
07-21 03:46:28.820  5037  5082 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
07-21 03:46:28.820  5037  5082 E AndroidRuntime: 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:814)
07-21 03:46:28.820  5037  5082 E AndroidRuntime: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2043)
07-21 03:46:28.820  5037  5082 E AndroidRuntime: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1858)
07-21 03:46:28.820  5037  5082 E AndroidRuntime: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:1528)
07-21 03:46:28.820  5037  5082 E AndroidRuntime: 	at com.github.andreyasadchy.xtra.ui.saved.downloads.DownloadsViewModel$delete$1.invokeSuspend(DownloadsViewModel.kt:742)
07-21 03:46:28.820  5037  5082 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
07-21 03:46:28.820  5037  5082 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
07-21 03:46:28.820  5037  5082 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:124)
07-21 03:46:28.820  5037  5082 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
07-21 03:46:28.820  5037  5082 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
07-21 03:46:28.820  5037  5082 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:820)
07-21 03:46:28.820  5037  5082 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
07-21 03:46:28.820  5037  5082 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)
07-21 03:46:28.820  5037  5082 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@3ec5784, Dispatchers.IO]
07-21 03:46:28.835  1310  5208 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
07-21 03:46:28.838  1310  1662 D Debug   : low && ship && 3rdparty app crash, do not dump
07-21 03:46:28.839  1310  5209 W ActivityManager: crash : com.github.andreyasadchy.xtra.debug,10247
07-21 03:46:28.840  1310  1662 W ActivityTaskManager:   Force finishing activity com.github.andreyasadchy.xtra.debug/com.github.andreyasadchy.xtra.ui.main.MainActivity

```

**Comment by tuxayo** [comment]
I didn't manage to reproduce the regressions I initially found in 2.45.5. (this ticket and the related ones) I wanted to compare with the next versions to confirm the fix. It's weird but anyway, nobody reported similar stuff since a month so it looks good.
Thanks again @crackededed for all the fixes :D
